export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_PLAYLIST = "FETCH_PLAYLIST";
export const RESET_PLAYLIST = "RESET_PLAYLIST";
export const SET_SONG_INDEX = "SET_SONG_INDEX";
export const SET_NEXT_INDEX = "SET_NEXT_INDEX ";

export const FETCH_METADATA = "FETCH_METADATA";

export const FETCH_MORE = "FETCH_MORE";
export const FETCH_LOAD_MORE = "FETCH_LOAD_MORE";

export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const FETCH_FAVORITES = "FETCH_FAVORITES";
