//Global errors actions
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//Home actions
export const COUNT_SONGS = "COUNT_SONGS";
//Auth actions
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
//Player actions
export const FETCH_PLAYLIST = "FETCH_PLAYLIST";
export const FETCH_PLAYLIST_START='FETCH_PLAYLIST_START'
export const FETCH_PLAYLIST_END='FETCH_PLAYLIST_END'
export const RESET_PLAYLIST = "RESET_PLAYLIST";
export const SET_SONG_INDEX = "SET_SONG_INDEX";
export const SET_NEXT_INDEX = "SET_NEXT_INDEX ";
//Music actions
export const FETCH_METADATA = "FETCH_METADATA";
export const FETCH_METADATA_START='FETCH_METADATA_START'
export const FETCH_METADATA_END='FETCH_METADATA_END'
//More actions
export const FETCH_MORE = "FETCH_MORE";
export const FETCH_MORE_START='FETCH_MORE_START'
export const FETCH_MORE_END='FETCH_MORE_END'
export const FETCH_LOAD_MORE = "FETCH_LOAD_MORE";
//Favorites actions
export const FETCH_FAVORITES = "FETCH_FAVORITES";
export const FETCH_FAVORITES_START='FETCH_FAVORITES_START'
export const FETCH_FAVORITES_END='FETCH_FAVORITES_END'
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
//Playlists actions
export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_START = "FETCH_PLAYLISTS_START";
export const FETCH_PLAYLISTS_END = "FETCH_PLAYLISTS_END";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
export const EDIT_PLAYLIST = "EDIT_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
//Delete song action
export const DELETE_SONG = "DELETE_SONG";